- package-lock.json
- package.json
- src/hooks.server.js
- src/lib/Card.svelte
- src/lib/CategoryDropdown.svelte
- src/lib/ContributeButton.svelte
- src/lib/DPGRating.svelte
- src/lib/LinkInput.svelte
- src/lib/Logo.svelte
- src/lib/Nav.svelte
- src/lib/ProjectBasics.svelte
- src/lib/ProjectCategory.svelte
- src/lib/Search.svelte
- src/lib/SearchBar.svelte
- src/lib/SignInForm.svelte
- src/lib/SignUp.svelte
- src/lib/SortDropdown.svelte
- src/lib/UserProfile.svelte
- src/routes/+page.server.js
- src/routes/+page.svelte
- src/routes/about/+page.svelte
- src/routes/createProject/+page.svelte
- src/routes/dpgs/+page.svelte
- src/routes/explore/+page.svelte
- src/routes/signIn/+page.svelte
- src/routes/singleProject/[id]/+page.svelte
> made design edits

- src/lib/Contribute.svelte
- src/lib/ContributeBtn.svelte
- src/lib/ContributeButton.svelte
- src/lib/Contributors.svelte
- src/lib/LeaderboardItem.svelte
- src/lib/ProjectAbout.svelte
- src/lib/ProjectMembers.svelte
- src/lib/ProjectNav.svelte
- src/lib/Resources.svelte
- src/lib/UpdateDetail.svelte
- src/lib/Updates.svelte
- src/lib/Wallet.svelte
- src/lib/apply.svelte
- src/routes/contribute/+page.svelte
- src/routes/contribute/[id]/apply/+page.svelte
- src/routes/singleProject/[id]/+page.svelte
made changes to the contribute page flow
> Contribute

- src/routes/singleProject/[id]/+page.svelte
- src/routes/singleProject/[id]/edit/+page.svelte
> Edit project

- src/routes/singleProject/[id]/+page.svelte
> added update button

- src/lib/ProjectCategory.svelte
- src/routes/explore/+page.svelte
- **fix(all projects): set all projects on by default**
- **fix(explore): inconsistent font**
> fix(explore page): buttons and filter

- .prettierrc
> feat(prettier): add config

- src/routes/singleProject/[id]/+page.svelte
> fix(project detail): remove team tab

- .gitignore
- src/lib/ProjectSection.svelte
- src/lib/UserProfile.svelte
> remove notification tab

- src/lib/apply.svelte
> changed text for comment section in contribute page

- src/lib/Card.svelte
- src/lib/utils/amountFormat.js
- src/routes/singleProject/[id]/+page.svelte
fixed the amount format for the Projects 
amount < 1000 -> shows normal
1000 -> 1k
1000000 -> 1M
1000000000 -> 1B
show total funding goal #30
> fixed the amount format for the Projects

- src/routes/+layout.svelte
> remove nav and footer from signin page

- src/lib/ProjectSection.svelte
> change bookmarks tab to follow

- src/lib/LinkInput.svelte
> create Project: text format

- src/lib/Card.svelte
Purely for demo purposes
- image will be taken from the image uploaded
- relevant SDGs to the project will be shown as an icon list
> fix(temp): temporarily show a random sdg image as placeholder

- src/lib/Nav.svelte
> fix: make signin/signup button rounder

- src/lib/server/repo/authUserRepo.js
- src/lib/server/repo/userProfileRepo.js
- src/lib/server/service/authUserService.js
- src/routes/(auth)/sign-up/+page.server.js
- src/routes/(auth)/sign-up/+page.svelte
- src/routes/api/projects/[id]/contribute/+server.js
- src/routes/api/signIn/+server.js
- src/routes/api/signUp/+server.js
- **Sign up Flow fixed**
- **#94**
> SignUp flow

- src/lib/Card.svelte
- src/lib/CategoryTag.svelte
> display image for the tag

- src/routes/profile/+page.svelte
after navigating to the create project page, when navigating back to the profile page, the project section gets distorted.
Now fixed.
> Profile page: project session distortion

- src/routes/project/[id]/+page.svelte
> removed the fetch project members since we no longer have the members tab

- src/routes/project/[id]/+page.svelte
> use reactive statements for dynamic banner and image updates

- src/lib/Nav.svelte
- src/lib/SearchModal.svelte
> fix the search function in the SearchModal

- src/routes/project/[id]/+page.svelte
> added the link to view the resource submitted

- src/lib/server/service/projectService.js
> Added timestamp on project update

- src/lib/UpdateDetail.svelte
> Added Date format for comments

- src/lib/ProfileForm.svelte
- src/lib/ProfileLinks.svelte
- src/lib/Settings.svelte
- src/lib/UserProfile.svelte
- src/lib/server/repo/userProfileRepo.js
- src/lib/server/service/profileService.js
- src/lib/server/validator/profileScheme.js
- src/routes/+layout.server.js
- src/routes/api/me/+server.js
- src/routes/api/profile/update/+server.js
- src/routes/profile/+page.svelte
- src/routes/profile/edit/+page.server.js
- src/routes/profile/edit/+page.svelte
- src/routes/project/create/+page.server.js
> User profile update

- package-lock.json
- package.json
- tailwind.config.js
> feat: add tailwindcss forms library

- package-lock.json
- package.json
- tailwind.config.js
`axios` was left because we use it in the `lib/server/github.js` file.
will be refactored to use fetch once we get to that file.
`package.json` was streamlined since we are not publishing an actual package to NPM registry
> chore: clean up unused dependencies

- src/lib/GitUpdate.svelte
- src/lib/Updates.svelte
> update git update design #279

- src/routes/explore/+page.svelte
> Fixed the load by category

- src/routes/project/[id]/+page.svelte
> fix: broken contributors tab on invalid github url

- src/lib/Issues.svelte
- src/routes/project/[id]/+page.svelte
> issue UI added #314

- src/lib/Issues.svelte
- src/routes/project/[id]/+page.svelte
> display open issues for project

- src/lib/UpdateDetail.svelte
- src/lib/server/service/projectService.js
- src/routes/api/projects/store/+server.js
- src/routes/profile/edit/+page.svelte
- src/routes/project/[id]/+page.svelte
- src/routes/project/[id]/contribute/+page.svelte
- src/routes/project/[id]/edit/+page.svelte
- src/routes/project/create/+page.server.js
- src/routes/project/create/+page.svelte
> disable buttons during CRUD operations to prevent duplicate actions

- src/lib/Updates.svelte
- src/lib/dpgStatus.svelte
- src/lib/server/repo/authUserRepo.js
- src/lib/server/service/aiService.js
- src/lib/server/service/dpgStatusService.js
- src/lib/server/service/helpers/projectHelpers.js
- src/lib/server/service/projectService.js
> Refactored the the OPEN AI response, and fix how the DPG status is shown using  instead of

- src/lib/server/github.js
- src/lib/server/service/aiService.js
- src/lib/server/service/githubWebhookService.js
- src/lib/server/service/helpers/projectHelpers.js
- src/routes/api/github/match/+server.js
- src/routes/project/create/+page.server.js
- src/routes/project/create/+page.svelte
> save matched projects from DPG registrar for a project

- src/app.html
- src/lib/Card.svelte
- src/lib/Issues.svelte
- src/lib/ProjectCategory.svelte
- src/lib/apply.svelte
- src/routes/+page.svelte
- src/routes/explore/+page.svelte
- src/routes/profile/(profile)/+layout.svelte
- src/routes/project/[id]/+page.svelte
- src/routes/project/[id]/contribute/+page.svelte
Fix the styling across the application for mobile and tablet
> fix(mobile): styling for mobile and tablet

- src/hooks.server.js
- Added apiProtection middleware to enforce authentication on protected API routes.
- Defined public API routes that do not require authentication.
- Implemented origin check for all API routes to enhance security.
> feat(api): implement API route protection and origin validation

- package-lock.json
- src/routes/resources/digital-public-good/+page.svelte
The original UI for the "What are Digital Public Goods" page features a simple, text-heavy layout with a light green header and a black background. The content is presented in a single column with minimal styling, using white text boxes for sections like "What are DPGs?" "Examples of DPGs," and "Why are DPGs important? DPG Standards". The design lacks visual hierarchy, with uniform text sizes and spacing, and the icons are basic, offering little to distinguish between sections. The overall look feels dated and functional but not engaging, with a focus on information delivery rather than user experience.
The updated UI for the "What are Digital Public Goods" page showcases a modern, visually appealing redesign that aligns with the project's flow. The addition of a vibrant purple "Ready to …
> Update Dpgs UI layout and styles

- src/routes/resources/pipeline/+page.svelte
- Added a detailed interactive pipeline page with a step-by-step explanation of the process.
- Implemented animated hero section, scroll-triggered animations, and real-time progress tracking.
- Each step now includes an icon and key benefits for better user engagement.
- Improved accessibility and responsiveness, adhering to the design system.
> feat(pipeline): enhance interactive pipeline page with animations and step details

- src/lib/Footer.svelte
make partner logos bigger on request and add tooltips
> fix(footer): add github link
